import { describe, expect, it } from 'vitest';
import { relationKinds } from '../../src/core/relations.js';
import { guardrailNames } from '../../src/policy/guardrails.js';
import { doctor, formatReport } from '../../src/ops/doctor.js';
import { memoryFileStore, staticDetector } from '../../src/substrate/index.js';

const AT = '2026-01-01T00:00:00.000Z';
const note = (id: string, extra: string[] = []) =>
  ['---', 'okf_version: 0.2', `id: ${id}`, `timestamp: ${AT}`, ...extra, '---', `# ${id}`].join(
    '\n',
  );

const noObsidian = staticDetector({});

describe('doctor is read-only', () => {
  it('writes nothing, even on a vault full of problems', async () => {
    const files = memoryFileStore({
      '/a.md': note('dup'),
      '/b.md': note('dup'),
      '/c.md': note('c', ['supersedes: [ghost]']),
    });
    const before = (await files.list()).sort();
    const beforeContent = await Promise.all(before.map((p) => files.read(p)));

    await doctor(files, noObsidian);

    expect((await files.list()).sort()).toEqual(before);
    expect(await Promise.all(before.map((p) => files.read(p)))).toEqual(beforeContent);
  });
});

describe('warnings are not failures (ADR-0021)', () => {
  it('a slug collision warns and does not fail', async () => {
    const r = await doctor(
      memoryFileStore({ '/a.md': note('dup'), '/b.md': note('dup') }),
      noObsidian,
    );
    expect(r.warnings.join(' ')).toMatch(/slug-collision/);
    expect(r.failures).toEqual([]);
  });

  it('a missing slug warns and does not fail', async () => {
    const r = await doctor(
      memoryFileStore({
        '/x.md': ['---', 'okf_version: 0.2', `timestamp: ${AT}`, '---', 'b'].join('\n'),
      }),
      noObsidian,
    );
    expect(r.warnings.join(' ')).toMatch(/path-as-identity/);
    expect(r.failures).toEqual([]);
  });

  it('a dangling edge warns and does not fail', async () => {
    const r = await doctor(
      memoryFileStore({ '/a.md': note('a', ['sources: [never-written]']) }),
      noObsidian,
    );
    expect(r.warnings.join(' ')).toMatch(/dangling-edge/);
    expect(r.failures).toEqual([]);
  });

  it('unparseable frontmatter warns and does not fail', async () => {
    const r = await doctor(
      memoryFileStore({ '/x.md': '---\nid: [unclosed\n---\nbody' }),
      noObsidian,
    );
    expect(r.warnings.join(' ')).toMatch(/did not parse/);
    expect(r.failures).toEqual([]);
  });

  it('a clean vault reports nothing at all', async () => {
    const r = await doctor(
      memoryFileStore({ '/a.md': note('a', ['sources: [b]']), '/b.md': note('b') }),
      noObsidian,
    );
    expect(r.warnings).toEqual([]);
    expect(r.failures).toEqual([]);
    expect(formatReport(r)).toContain('no problems found');
  });
});

describe('every registered relation detective runs', () => {
  it('reports one check per registered relation, by name', async () => {
    const r = await doctor(memoryFileStore({ '/a.md': note('a') }), noObsidian);
    expect(r.detectives.map((d) => d.relation)).toEqual(relationKinds());
    for (const d of r.detectives) expect(d.check.length).toBeGreaterThan(0);
  });

  it('a detective finds a container that does not exist', async () => {
    const r = await doctor(
      memoryFileStore({ '/a.md': note('a', ['part-of: [no-such-container]']) }),
      noObsidian,
    );
    const partOf = r.detectives.find((d) => d.relation === 'part-of')!;
    expect(partOf.hits.join(' ')).toMatch(/no-such-container/);
  });

  it('reports clean when a detective finds nothing', async () => {
    const r = await doctor(
      memoryFileStore({ '/a.md': note('a', ['part-of: [b]']), '/b.md': note('b') }),
      noObsidian,
    );
    expect(r.detectives.every((d) => d.hits.length === 0)).toBe(true);
    expect(formatReport(r)).toContain('clean');
  });
});

describe('nested roots and derived state', () => {
  it('reports a skipped nested root (TD-004)', async () => {
    const r = await doctor(
      memoryFileStore({
        '/a.md': note('a'),
        '/private/.engram/c.json': '{}',
        '/private/x.md': note('x'),
      }),
      noObsidian,
    );
    expect(r.warnings.join(' ')).toMatch(/nested-root-skipped/);
  });

  it('flags a derived path engram did not write, citing regenerate-never-merge', async () => {
    const r = await doctor(
      memoryFileStore({ '/index.md': '# my hand-written index', '/a.md': note('a') }),
      noObsidian,
    );
    expect(r.warnings.join(' ')).toMatch(/derived-not-generated/);
    expect(r.warnings.join(' ')).toMatch(/regenerate, never merge/);
  });

  it('does not flag a derived file engram did write', async () => {
    const generated = '<!-- GENERATED by engram reindex. -->\n# Index\n';
    const r = await doctor(memoryFileStore({ '/index.md': generated }), noObsidian);
    expect(r.warnings.join(' ')).not.toMatch(/derived-not-generated/);
  });
});

describe('Obsidian is detected, not configured (ADR-0025/0028)', () => {
  it('reports the link-format expectation when Obsidian is present', async () => {
    const r = await doctor(
      memoryFileStore({ '/a.md': note('a') }),
      staticDetector({ obsidian: true }),
    );
    expect(r.warnings.join(' ')).toMatch(/absolute \+ markdown/);
    expect(r.warnings.join(' ')).toMatch(/never rewrites link targets/);
  });

  it('says nothing about Obsidian when it is absent', async () => {
    const r = await doctor(memoryFileStore({ '/a.md': note('a') }), noObsidian);
    expect(r.warnings.join(' ')).not.toMatch(/Obsidian/);
  });
});

describe('guardrail detectives run in doctor (v2-overview §7)', () => {
  it('reports one check per guardrail in force, by name', async () => {
    const r = await doctor(memoryFileStore({ '/a.md': note('a') }), noObsidian);
    expect(r.guardrails.map((g) => g.rule)).toEqual(guardrailNames());
    for (const g of r.guardrails) expect(g.prevents.length).toBeGreaterThan(0);
  });

  /**
   * The point of the detective half: this note was never written through the gate.
   * It is what an Obsidian edit or an agent shell write looks like from doctor's
   * side, and the preventive half could never have seen it.
   */
  it('catches an uncited synthesis that never passed the gate', async () => {
    const r = await doctor(memoryFileStore({ '/synthesis-x.md': note('synthesis-x') }), noObsidian);
    const hits = r.guardrails.find((g) => g.rule === 'require-sources')!.hits;
    expect(hits.join(' ')).toMatch(/no sources/);
    expect(r.warnings.join(' ')).toMatch(/\[guardrail:require-sources\]/);
  });

  it('a guardrail hit is a warning, not a failure', async () => {
    const r = await doctor(memoryFileStore({ '/synthesis-x.md': note('synthesis-x') }), noObsidian);
    expect(r.failures).toEqual([]);
  });

  it('honours a narrowed configuration', async () => {
    const r = await doctor(memoryFileStore({ '/a.md': note('a') }), noObsidian, {
      enabled: ['require-sources'],
    });
    expect(r.guardrails.map((g) => g.rule)).toEqual(['require-sources']);
  });

  it('formats guardrail results, saying what each prevents', async () => {
    const out = formatReport(await doctor(memoryFileStore({ '/a.md': note('a') }), noObsidian));
    expect(out).toMatch(/guardrail detectives \(6 in force\)/);
    expect(out).toMatch(/writes the gate never saw/);
  });
});
