import { describe, expect, it } from 'vitest';
import { init, pointerLine } from '../../src/ops/init.js';
import { fixedClock, memoryFileStore } from '../../src/substrate/index.js';

const AT = '2026-08-17T09:00:00.000Z';

/**
 * Adoption — `init` into a vault that already exists (BUG-005, BUG-006).
 *
 * This is the common real path and it was the broken one. Engram scaffolded its
 * five-folder reference tree into vaults that already had a shape, which ADR-0023
 * says it has no opinion about; on a case-insensitive filesystem `projects/` even
 * resolved into an existing `Projects/` and dropped a `.gitkeep` beside real notes.
 */
describe('adopting a vault that already has notes', () => {
  const existing = () =>
    memoryFileStore({
      '/Daily Notes/2026-08-01.md': '# Meeting with Sam',
      '/Projects/Q3 plan.md': '# Q3 plan',
    });

  it('does not impose the reference tree', async () => {
    const files = existing();
    const { created } = await init(files, fixedClock(AT));

    for (const dir of ['inbox', 'concepts', 'decisions', 'sources', 'projects']) {
      expect(created).not.toContain(`/${dir}/.gitkeep`);
    }
  });

  it('says why, rather than silently doing less', async () => {
    const { notes } = await init(existing(), fixedClock(AT));
    expect(notes.join(' ')).toMatch(/already has notes/);
    expect(notes.join(' ')).toMatch(/no opinion about your folders/);
  });

  it('still writes what every vault needs', async () => {
    const { created } = await init(existing(), fixedClock(AT));
    expect(created).toContain('/.engram/config.json');
    expect(created).toContain('/.engram/guardrails.md');
    expect(created).toContain('/.gitignore');
  });

  it('leaves the existing notes untouched', async () => {
    const files = existing();
    await init(files, fixedClock(AT));
    expect(await files.read('/Projects/Q3 plan.md')).toBe('# Q3 plan');
    expect(await files.read('/Daily Notes/2026-08-01.md')).toBe('# Meeting with Sam');
  });

  it('DOES scaffold the tree for a genuinely empty vault', async () => {
    const { created } = await init(memoryFileStore(), fixedClock(AT));
    expect(created).toContain('/inbox/.gitkeep');
    expect(created).toContain('/concepts/.gitkeep');
  });

  /** A vault holding only derived state from a previous run is still empty. */
  it('treats derived and reserved files as not-authored', async () => {
    const files = memoryFileStore({
      '/index.md': '<!-- GENERATED by engram reindex. -->',
      '/AGENTS.md': '# contract',
    });
    expect((await init(files, fixedClock(AT))).created).toContain('/inbox/.gitkeep');
  });
});

/**
 * BUG-006. Leaving a hand-written CLAUDE.md alone is correct — it may carry
 * instructions engram knows nothing about. But the pointer's only job is to route
 * the agent, so a skip means the agent is never routed, and "left alone" does not
 * convey that.
 */
describe('an agent left unrouted is reported, not just skipped', () => {
  it('warns that the agent will not find the contract, and names the line to add', async () => {
    const files = memoryFileStore({ '/CLAUDE.md': '# my own instructions\n' });
    const { notes } = await init(files, fixedClock(AT));

    const said = notes.join('\n');
    expect(said).toMatch(/will NOT find the contract/);
    expect(said).toContain('AGENTS.md');
  });

  it('the suggested line actually points at the contract', async () => {
    expect(pointerLine('/CLAUDE.md')).toContain('](AGENTS.md)');
    expect(pointerLine('/.antigravity/AGENTS.md')).toContain('](../AGENTS.md)');
  });

  it('stays quiet when the existing file already references the contract', async () => {
    const files = memoryFileStore({ '/CLAUDE.md': 'see [AGENTS.md](AGENTS.md)\n' });
    const { notes } = await init(files, fixedClock(AT));
    expect(notes.join(' ')).not.toMatch(/will NOT find/);
  });

  it('never overwrites the file it warns about', async () => {
    const mine = '# mine\n\nkeep this\n';
    const files = memoryFileStore({ '/CLAUDE.md': mine });
    await init(files, fixedClock(AT));
    expect(await files.read('/CLAUDE.md')).toBe(mine);
  });
});
