import { describe, expect, it } from 'vitest';
import { init } from '../../src/ops/init.js';
import { fixedClock, memoryFileStore } from '../../src/substrate/index.js';

const AT = '2026-08-17T09:00:00.000Z';

/**
 * Adoption — `init` into a vault that already exists (BUG-005, BUG-006).
 *
 * This is the common real path and it was the broken one. Engram scaffolded its
 * five-folder reference tree into vaults that already had a shape, which ADR-0023
 * says it has no opinion about; on a case-insensitive filesystem `projects/` even
 * resolved into an existing `Projects/` and dropped a `.gitkeep` beside real notes.
 */
describe('adopting a vault that already has notes', () => {
  const existing = () =>
    memoryFileStore({
      '/Daily Notes/2026-08-01.md': '# Meeting with Sam',
      '/Projects/Q3 plan.md': '# Q3 plan',
    });

  it('does not impose the reference tree', async () => {
    const files = existing();
    const { created } = await init(files, fixedClock(AT));

    for (const dir of ['raw', 'concepts', 'decisions', 'sources', 'projects']) {
      expect(created).not.toContain(`/${dir}/.gitkeep`);
    }
  });

  it('says why, rather than silently doing less', async () => {
    const { notes } = await init(existing(), fixedClock(AT));
    expect(notes.join(' ')).toMatch(/already has notes/);
    expect(notes.join(' ')).toMatch(/no opinion about your folders/);
  });

  it('still writes what every vault needs', async () => {
    const { created } = await init(existing(), fixedClock(AT));
    expect(created).toContain('/.engram/config.json');
    expect(created).toContain('/engram/guardrails.md');
    expect(created).toContain('/.gitignore');
  });

  it('leaves the existing notes untouched', async () => {
    const files = existing();
    await init(files, fixedClock(AT));
    expect(await files.read('/Projects/Q3 plan.md')).toBe('# Q3 plan');
    expect(await files.read('/Daily Notes/2026-08-01.md')).toBe('# Meeting with Sam');
  });

  it('DOES scaffold the tree for a genuinely empty vault', async () => {
    const { created } = await init(memoryFileStore(), fixedClock(AT));
    expect(created).toContain('/raw/.gitkeep');
  });

  /** A vault holding only derived state from a previous run is still empty. */
  it('treats derived and reserved files as not-authored', async () => {
    const files = memoryFileStore({
      '/index.md': '<!-- GENERATED by engram reindex. -->',
      '/AGENTS.md': '# contract',
    });
    expect((await init(files, fixedClock(AT))).created).toContain('/raw/.gitkeep');
  });
});

/**
 * BUG-006's real fix. Until ADR-0017 was restored, `init` left a hand-written
 * CLAUDE.md alone and told you to paste a line in yourself — correct about
 * ownership, useless in practice, and it left the agent with no contract until you
 * did it. The contract is now spliced into a marked region instead.
 */
describe('a hand-written agent file gets the contract without losing anything', () => {
  it('keeps what the user wrote and adds the contract', async () => {
    const files = memoryFileStore({ '/CLAUDE.md': '# mine\n\nkeep this\n' });
    await init(files, fixedClock(AT));

    const after = (await files.read('/CLAUDE.md')) ?? '';
    expect(after).toContain('keep this');
    expect(after).toContain('BEGIN ENGRAM CONTRACT');
    expect(after).toContain('Never validates, never fails');
  });

  it('says so, rather than leaving the merge silent', async () => {
    const files = memoryFileStore({ '/CLAUDE.md': '# mine\n' });
    const { notes } = await init(files, fixedClock(AT));
    expect(notes.join(' ')).toMatch(/left everything you wrote untouched/);
  });

  it('does not report a merge for a file it created itself', async () => {
    const { notes } = await init(memoryFileStore(), fixedClock(AT));
    expect(notes.join(' ')).not.toMatch(/left everything you wrote untouched/);
  });

  it('running init twice does not stack the block', async () => {
    const files = memoryFileStore({ '/CLAUDE.md': '# mine\n' });
    await init(files, fixedClock(AT));
    await init(files, fixedClock(AT));
    expect(((await files.read('/CLAUDE.md')) ?? '').split('BEGIN ENGRAM CONTRACT')).toHaveLength(2);
  });
});
