import { describe, expect, it } from 'vitest';
import { init, STRUCTURES } from '../../src/ops/init.js';
import { reindex } from '../../src/ops/reindex.js';
import { BEGIN, END } from '../../src/surface/adapters.js';
import { fixedClock, memoryFileStore } from '../../src/substrate/index.js';

const AT = '2026-01-01T00:00:00.000Z';
const clock = fixedClock('2026-08-12T09:00:00.000Z');
const note = (id: string, extra: string[] = []) =>
  ['---', 'okf_version: 0.2', `id: ${id}`, `timestamp: ${AT}`, ...extra, '---', `# ${id}`].join(
    '\n',
  );

const snapshot = async (files: Awaited<ReturnType<typeof memoryFileStore>>) => {
  const paths = (await files.list()).sort();
  const contents = await Promise.all(paths.map((p) => files.read(p)));
  return Object.fromEntries(paths.map((p, i) => [p, contents[i]]));
};

describe('reindex is idempotent (ADR-0029)', () => {
  it('a second run changes nothing', async () => {
    const files = memoryFileStore({ '/a.md': note('a', ['part-of: [b]']), '/b.md': note('b') });
    await reindex(files, clock);
    const first = await snapshot(files);
    await reindex(files, clock);
    expect(await snapshot(files)).toEqual(first);
  });

  it('a run with a different clock still changes nothing', async () => {
    // The proof that no generated file embeds a generation timestamp.
    const files = memoryFileStore({ '/a.md': note('a') });
    await reindex(files, clock);
    const first = await snapshot(files);
    await reindex(files, fixedClock('2099-12-31T23:59:59.000Z'));
    expect(await snapshot(files)).toEqual(first);
  });
});

describe('derived state is safe to delete (ADR-0029)', () => {
  it('deleting every derived file and rebuilding restores it byte-identical', async () => {
    const files = memoryFileStore({
      '/a.md': note('a', ['part-of: [container]', 'supersedes: [old]']),
      '/b.md': note('b'),
      '/old.md': note('old'),
      '/container.md': note('container'),
    });
    const { written } = await reindex(files, clock);
    const before = await snapshot(files);

    // "Deleting derived state must always be safe." Simulate it.
    const survivors = memoryFileStore(
      Object.fromEntries(
        Object.entries(before)
          .filter(([p]) => !written.includes(p))
          .map(([p, c]) => [p, c as string]),
      ),
    );
    await reindex(survivors, clock);

    expect(await snapshot(survivors)).toEqual(before);
  });
});

describe('reindex reports what the walker found', () => {
  it('surfaces a skipped nested root rather than swallowing it', async () => {
    const files = memoryFileStore({
      '/a.md': note('a'),
      '/private/.engram/c.json': '{}',
      '/private/secret.md': note('secret'),
    });
    const { findings, counts } = await reindex(files, clock);
    expect(findings.map((f) => f.code)).toContain('nested-root-skipped');
    expect(counts.nodes).toBe(1);
    const index = (await files.read('/index.md'))!;
    expect(index).not.toContain('secret');
  });

  it('surfaces read warnings, e.g. a node with no slug', async () => {
    const files = memoryFileStore({
      '/x.md': ['---', 'okf_version: 0.2', `timestamp: ${AT}`, '---', 'b'].join('\n'),
    });
    const { warnings } = await reindex(files, clock);
    expect(warnings.join(' ')).toMatch(/path-as-identity/);
  });

  it('an empty vault reindexes without error', async () => {
    const { written, counts } = await reindex(memoryFileStore(), clock);
    expect(written).toEqual([
      '/index.md',
      '/views/superseded.md',
      '/views/recent.md',
      '/views/orphans.md',
      '/AGENTS.md',
      // Every agent's own file is rendered here too — ADR-0017: an agent that
      // loads CLAUDE.md does not reliably go and read a referenced AGENTS.md,
      // so a pointer would leave the contract invisible to it.
      '/.antigravity/AGENTS.md',
      '/CLAUDE.md',
      '/GEMINI.md',
    ]);
    expect(counts.nodes).toBe(0);
  });

  it('regenerates AGENTS.md from the live registries', async () => {
    const files = memoryFileStore();
    await reindex(files, clock);
    const md = (await files.read('/AGENTS.md'))!;
    expect(md).toContain('GENERATED by engram reindex');
    expect(md).toContain('`supersedes`');
    expect(md).toContain('`require-sources`');
  });

  it('OVERWRITES a hand-edited AGENTS.md — it is generated, not authored', async () => {
    // Deliberate, and the reason the file says so at the top. A contract that
    // drifts from the code is worse than none, so the code wins.
    const files = memoryFileStore({ '/AGENTS.md': '# my own notes to the agent' });
    await reindex(files, clock);
    expect(await files.read('/AGENTS.md')).not.toContain('my own notes');
  });
});

describe('init', () => {
  it('scaffolds raw/ and nothing else — the one directory the design requires', async () => {
    const files = memoryFileStore();
    const { created, reindexed } = await init(files, clock);

    // `capture` must put bytes somewhere before anything is decided about them.
    expect(created).toContain('/raw/.gitkeep');
    // The other four folders were a suggestion, and engram claims no opinion
    // about your shape (ADR-0023). The suggestion lives in AGENTS.md instead.
    for (const dir of ['concepts', 'decisions', 'sources', 'projects']) {
      expect(created).not.toContain(`/${dir}/.gitkeep`);
    }
    expect(reindexed.length).toBeGreaterThan(0);
  });

  it('gitignores derived state (ADR-0029)', async () => {
    const files = memoryFileStore();
    await init(files, clock);
    const gitignore = (await files.read('/.gitignore'))!;
    expect(gitignore).toContain('/views/');
    expect(gitignore).toContain('/index.md');
  });

  it('appends to an existing gitignore rather than clobbering it', async () => {
    const files = memoryFileStore({ '/.gitignore': 'node_modules/\n.env\n' });
    await init(files, clock);
    const gitignore = (await files.read('/.gitignore'))!;
    expect(gitignore).toContain('node_modules/');
    expect(gitignore).toContain('.env');
    expect(gitignore).toContain('/views/');
  });

  it('is non-destructive — never overwrites authored content', async () => {
    const mine = '# my own gitignore rules';
    const files = memoryFileStore({ '/.engram/config.json': mine });
    const { created, skipped } = await init(files, clock);
    expect(skipped).toContain('/.engram/config.json');
    expect(created).not.toContain('/.engram/config.json');
    expect(await files.read('/.engram/config.json')).toBe(mine);
  });

  it('is safe to run twice', async () => {
    const files = memoryFileStore();
    await init(files, clock);
    const first = await snapshot(files);
    const second = await init(files, clock);
    expect(second.created).toEqual([]);
    // Byte-identical including the regenerated AGENTS.md, which is what makes
    // regeneration quiet rather than a permanent source of diffs.
    expect(await snapshot(files)).toEqual(first);
  });

  it('rejects an unknown structure, and says what it ships', async () => {
    await expect(init(memoryFileStore(), clock, 'para')).rejects.toThrow(/engram ships only/);
  });

  it('ships exactly one structure — presets are opinions engram does not hold', () => {
    expect([...STRUCTURES]).toEqual(['default']);
  });

  it('produces a vault the walker does not treat the sidecar as nested', async () => {
    const files = memoryFileStore();
    await init(files, clock);
    const { findings } = await reindex(files, clock);
    expect(findings).toEqual([]);
  });
});

/**
 * ADR-0017 over ADR-0011: the contract is rendered **in full** into each agent's
 * own file, not pointed at.
 *
 * Phase 15 shipped pointers, citing ADR-0011 without noticing that ADR-0017
 * amends it. A pointer looks tidy and fails silently — `CLAUDE.md` said "read
 * AGENTS.md", Claude Code often did not, and the contract stayed invisible to
 * the agent it was written for.
 */
describe('every agent gets the contract itself, not a pointer to it', () => {
  it('renders the real contract into each agent file', async () => {
    const files = memoryFileStore();
    await reindex(files, clock);

    for (const path of ['/CLAUDE.md', '/GEMINI.md', '/.antigravity/AGENTS.md']) {
      const contract = (await files.read(path))!;
      // Actual contract content, not a reference to where it lives.
      expect(contract).toContain('Never validates, never fails');
      expect(contract).toContain(BEGIN);
      expect(contract).toContain(END);
    }
  });

  it("preserves a user's own file, splicing engram's region below it", async () => {
    const mine = '# My own notes to Claude\n\nAlways ask before touching /decisions/.';
    const files = memoryFileStore({ '/CLAUDE.md': mine });
    const { contracts } = await reindex(files, clock);

    expect(contracts.merged).toContain('/CLAUDE.md');
    const after = (await files.read('/CLAUDE.md'))!;
    // Their text survives byte for byte, and comes first.
    expect(after.startsWith(mine)).toBe(true);
    expect(after).toContain('Never validates, never fails');
  });

  it('replaces only its own region on a second run', async () => {
    const mine = '# Mine\n\nkeep this line.';
    const files = memoryFileStore({ '/CLAUDE.md': mine });
    await reindex(files, clock);
    await reindex(files, clock);

    const after = (await files.read('/CLAUDE.md'))!;
    expect(after.startsWith(mine)).toBe(true);
    // Exactly one region — the block is replaced, never appended twice.
    expect(after.split(BEGIN)).toHaveLength(2);
  });

  /**
   * The bug this file caught: a generated contract file being read back as a
   * knowledge node, so run 1 and run 2 disagreed and idempotence failed.
   */
  it('never counts its own contract files as authored notes', async () => {
    const files = memoryFileStore({ '/a.md': note('a') });
    expect((await reindex(files, clock)).counts.nodes).toBe(1);
    expect((await reindex(files, clock)).counts.nodes).toBe(1);
  });
});
