import { describe, expect, it } from 'vitest';
import { AGENTS, pointerFor, writePointers } from '../../src/surface/adapters.js';
import { generateAgentsMd } from '../../src/surface/agents-md.js';
import { guardrailNames } from '../../src/policy/guardrails.js';
import { memoryFileStore } from '../../src/substrate/index.js';

describe('a pointer contains no contract content', () => {
  /**
   * The whole point. ADR-0011 converges on AGENTS.md; a pointer that restated any
   * of it would be a second copy, and the second copy is the one that goes stale.
   * Phase 9 already paid for that lesson with the codec's hardcoded relation list.
   */
  it.each(AGENTS)('$name says nothing AGENTS.md says', (agent) => {
    const pointer = pointerFor(agent);
    const contract = generateAgentsMd({ enabled: guardrailNames() });

    for (const claim of [
      'Never validates, never fails',
      'cannot infer a relationship',
      'may be empty',
      'repair is trivial',
    ]) {
      expect(contract).toContain(claim);
      expect(pointer).not.toContain(claim);
    }
    for (const rule of guardrailNames()) expect(pointer).not.toContain(rule);
  });

  it('points at AGENTS.md and says to read it first', () => {
    const pointer = pointerFor(AGENTS[0]!);
    expect(pointer).toContain('AGENTS.md');
    expect(pointer).toMatch(/Read it first/i);
  });

  it('says why it is deliberately empty, so nobody helpfully fills it in', () => {
    expect(pointerFor(AGENTS[0]!)).toMatch(/second copy of the rules is the copy/);
  });

  it('declares itself generated', () => {
    expect(pointerFor(AGENTS[0]!)).toContain('GENERATED by engram');
  });

  it('resolves the relative path correctly from a nested location', () => {
    const nested = {
      name: 'x',
      instructionsPath: '/.deeply/nested/AGENTS.md',
      why: 'test',
    };
    expect(pointerFor(nested)).toContain('](../../AGENTS.md)');
  });

  it('uses a bare path from the root', () => {
    expect(pointerFor({ name: 'x', instructionsPath: '/X.md', why: 't' })).toContain(
      '](AGENTS.md)',
    );
  });
});

describe('adding an agent is adding a descriptor', () => {
  it('a descriptor alone produces a pointer — no code, no template, no branch', async () => {
    const files = memoryFileStore();
    const invented = {
      name: 'some-future-agent',
      instructionsPath: '/FUTURE.md',
      why: 'it looks for FUTURE.md',
    };
    const { written } = await writePointers(files, [invented]);
    expect(written).toEqual(['/FUTURE.md']);
    expect(await files.read('/FUTURE.md')).toContain('AGENTS.md');
  });

  it('every shipped descriptor explains why it needs a pointer at all', () => {
    // Agents that read AGENTS.md natively should have no descriptor. The `why`
    // field is what stops the list quietly accumulating ones that do.
    for (const agent of AGENTS) {
      expect(agent.why.length).toBeGreaterThan(0);
      expect(agent.instructionsPath).not.toBe('/AGENTS.md');
    }
  });

  it('ships a Claude pointer, since Claude Code looks for CLAUDE.md', () => {
    expect(AGENTS.map((a) => a.instructionsPath)).toContain('/CLAUDE.md');
  });
});

describe('writing pointers is non-destructive', () => {
  it('writes a pointer for each agent when none exist', async () => {
    const files = memoryFileStore();
    const { written, skipped } = await writePointers(files);
    expect(written).toEqual(AGENTS.map((a) => a.instructionsPath).sort());
    expect(skipped).toEqual([]);
  });

  it("leaves a user's own CLAUDE.md alone", async () => {
    // It may carry instructions engram knows nothing about. Overwriting it to say
    // "read AGENTS.md" would destroy more than it explains.
    const mine = '# My own notes to Claude\n\nAlways run the tests.';
    const files = memoryFileStore({ '/CLAUDE.md': mine });
    const { written, skipped } = await writePointers(files);
    expect(skipped).toContain('/CLAUDE.md');
    expect(written).not.toContain('/CLAUDE.md');
    expect(await files.read('/CLAUDE.md')).toBe(mine);
  });

  it('is safe to run twice', async () => {
    const files = memoryFileStore();
    await writePointers(files);
    const { written, skipped } = await writePointers(files);
    expect(written).toEqual([]);
    expect(skipped).toEqual(AGENTS.map((a) => a.instructionsPath).sort());
  });
});
