import { describe, expect, it } from 'vitest';
import { registerRelation, relationKinds } from '../../src/core/relations.js';
import { guardrailNames } from '../../src/policy/guardrails.js';
import { generateAgentsMd } from '../../src/surface/agents-md.js';

const all = { enabled: guardrailNames() };

/**
 * The contract is generated from the same registries the code reads, because a
 * contract that drifts from the code is worse than none — an agent that trusts it
 * confidently does the wrong thing. Phase 9 demonstrated exactly that failure with
 * the codec's hardcoded relation list.
 */
describe('AGENTS.md is derived from the code, not a template', () => {
  it('lists every registered relation with its meaning', () => {
    const md = generateAgentsMd(all);
    for (const name of relationKinds()) expect(md).toContain(`\`${name}\``);
  });

  it('says which relations invalidate their target', () => {
    const md = generateAgentsMd(all);
    // supersedes does; part-of and sources do not. Getting this wrong in prose
    // would teach an agent that reorganising a tree marks its contents stale.
    expect(md).toMatch(/\|\s*`supersedes`\s*\|[^|]*\|\s*\*\*yes\*\*\s*\|/);
    expect(md).toMatch(/\|\s*`part-of`\s*\|[^|]*\|\s*no\s*\|/);
  });

  it('picks up a newly registered relation with no template edit', () => {
    registerRelation({
      name: 'depends-on',
      invalidatesTarget: false,
      meaning: 'this node requires the target to hold',
      detective: 'find depends-on targets that no longer exist',
    });
    const md = generateAgentsMd(all);
    expect(md).toContain('`depends-on`');
    expect(md).toContain('this node requires the target to hold');
  });

  it('lists every guardrail in force with what it prevents', () => {
    const md = generateAgentsMd(all);
    for (const name of guardrailNames()) expect(md).toContain(`\`${name}\``);
    expect(md).toContain('losing the record of what you used to believe');
  });

  it('reflects a narrowed configuration rather than the full set', () => {
    const md = generateAgentsMd({ enabled: ['require-sources'] });
    expect(md).toContain('`require-sources`');
    expect(md).not.toContain('| `rate-limit` |');
  });

  it('says so when no guardrails are enabled', () => {
    expect(generateAgentsMd({ enabled: [] })).toContain('_None enabled._');
  });

  it('states the scopes and limits actually configured', () => {
    const md = generateAgentsMd({
      enabled: ['path-scope', 'rate-limit', 'propose-only'],
      pathScope: ['/concepts/'],
      proposeOnly: ['/decisions/'],
      rateLimit: 20,
    });
    expect(md).toContain('permitted only under `/concepts/`');
    expect(md).toContain('`/decisions/` need human review');
    expect(md).toContain('at most 20 new nodes per run');
  });

  it('omits scope sections that are not configured', () => {
    const md = generateAgentsMd({ enabled: ['no-delete'] });
    expect(md).not.toContain('Path scope:');
    expect(md).not.toContain('Rate limit:');
  });
});

describe('the contract states the load-bearing invariants', () => {
  const md = generateAgentsMd(all);

  it('says capture never rejects', () => {
    expect(md).toMatch(/Never validates, never fails/);
    expect(md).toMatch(/Losing a thought is the only real/);
  });

  it('says engram runs no model and the agent authors relations', () => {
    expect(md).toMatch(/no network calls and runs no model/i);
    expect(md).toMatch(/cannot infer a relationship/);
  });

  it('says a wrong relation is cheap to fix — the actual mitigation', () => {
    expect(md).toMatch(/repair is trivial, so extraction does not have to be perfect/);
  });

  it('says an empty node is valid', () => {
    expect(md).toMatch(/may be empty/);
  });

  it('warns off nested vault roots', () => {
    expect(md).toMatch(/own `\.engram\/` is a separate vault/);
  });

  it('says derived files are generated and must not be edited', () => {
    expect(md).toContain('are **generated**. Do not edit them');
  });
});

describe('regeneration is idempotent', () => {
  it('embeds no timestamp, so reindex does not dirty the tree', () => {
    expect(generateAgentsMd(all)).toBe(generateAgentsMd(all));
  });

  it('declares itself generated and safe to delete', () => {
    const md = generateAgentsMd(all);
    expect(md).toContain('GENERATED by engram reindex');
    expect(md).toContain('regenerate — never merge');
  });
});
