import { existsSync, mkdirSync, renameSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

export interface WriteOptions {
  /** Overwrite an existing file. Off by default (non-destructive — NFR-4). */
  force?: boolean;
}

export function ensureDir(dir: string): void {
  mkdirSync(dir, { recursive: true });
}

function atomicWrite(absPath: string, content: string): void {
  ensureDir(dirname(absPath));
  const tmp = `${absPath}.tmp-${process.pid}`;
  writeFileSync(tmp, content);
  renameSync(tmp, absPath);
}

/**
 * Write a user-content file only if it does not already exist (unless `force`).
 * Returns true if written, false if skipped to avoid clobbering. Non-destructive
 * by default (NFR-4 / Principle 6).
 */
export function writeFileSafe(absPath: string, content: string, opts: WriteOptions = {}): boolean {
  if (existsSync(absPath) && !opts.force) return false;
  atomicWrite(absPath, content);
  return true;
}

/**
 * Always (over)write a tool-owned file atomically (index.md, log.md). These are
 * fully regenerated by the tool, so overwriting is expected and safe.
 */
export function writeFileManaged(absPath: string, content: string): void {
  atomicWrite(absPath, content);
}
