/**
 * Agent adapters — native instruction pointers, and nothing else.
 *
 * [ADR-0011](../../specs/decisions/0011-adapters-converge-on-agents-md.md)'s
 * decision is convergence on `AGENTS.md`. Its *implementation* section describes
 * v1's per-agent command surfaces — `.claude/commands/`, `.codex/prompts/` — which
 * existed to reach v1's operations. MCP is that surface now.
 *
 * So an adapter emits a **pointer** and carries no contract content. That is not a
 * simplification for its own sake: every duplicated instruction is a second place
 * the contract can drift, and Phase 9 already demonstrated what that costs when the
 * codec's hardcoded relation list silently disagreed with the registry.
 *
 * **Adding an agent is adding a descriptor.** No code, no template, no branch.
 */

import type { FileStore } from '../core/ports.js';

export interface AgentDescriptor {
  /** How the agent is referred to. */
  name: string;
  /** The file this agent looks for, relative to the vault root. */
  instructionsPath: string;
  /** Why it needs a pointer at all — agents that read AGENTS.md natively do not. */
  why: string;
}

/**
 * Agents that look for a filename other than `AGENTS.md`.
 *
 * Codex and any agent following the AGENTS.md convention are deliberately absent:
 * they already read the contract, so emitting anything for them would be a file that
 * exists only to be maintained.
 */
export const AGENTS: AgentDescriptor[] = [
  {
    name: 'claude',
    instructionsPath: '/CLAUDE.md',
    why: 'Claude Code looks for CLAUDE.md and would not otherwise find the contract',
  },
  {
    name: 'antigravity',
    instructionsPath: '/.antigravity/AGENTS.md',
    why: 'Antigravity reads instructions from its own directory',
  },
  {
    name: 'gemini',
    instructionsPath: '/GEMINI.md',
    why: 'the Gemini CLI looks for GEMINI.md and would not otherwise find the contract',
  },
];

/**
 * The pointer body.
 *
 * Deliberately says almost nothing. Anything stated here would be a second copy of
 * something `AGENTS.md` already says, and the second copy is the one that goes stale.
 */
export function pointerFor(agent: AgentDescriptor): string {
  const depth = agent.instructionsPath.split('/').filter(Boolean).length - 1;
  const target = `${'../'.repeat(depth)}AGENTS.md`;
  return [
    `<!-- GENERATED by engram. Points at the contract; contains none of it. -->`,
    '',
    `# ${agent.name}`,
    '',
    `This is an engram vault. **The contract is [AGENTS.md](${target}).** Read it first.`,
    '',
    'Nothing is duplicated here on purpose: a second copy of the rules is the copy',
    'that goes stale.',
    '',
  ].join('\n');
}

export interface AdapterResult {
  written: string[];
  skipped: string[];
}

/**
 * Emit a pointer for each agent that needs one.
 *
 * **Non-destructive**, like `init`: an existing file is left alone. A user's own
 * `CLAUDE.md` may carry instructions engram knows nothing about, and overwriting it
 * to say "read AGENTS.md" would destroy more than it explains.
 */
export async function writePointers(
  files: FileStore,
  agents: AgentDescriptor[] = AGENTS,
): Promise<AdapterResult> {
  const written: string[] = [];
  const skipped: string[] = [];

  for (const agent of agents) {
    if (await files.exists(agent.instructionsPath)) {
      skipped.push(agent.instructionsPath);
      continue;
    }
    await files.write(agent.instructionsPath, pointerFor(agent));
    written.push(agent.instructionsPath);
  }

  return { written: written.sort(), skipped: skipped.sort() };
}
