/**
 * `AGENTS.md` — the entry contract for any agent working in this vault (ADR-0011).
 *
 * **Generated, never hand-written.** It names the operations, the guardrails
 * actually in force, and the closed relation set read from the registry. A contract
 * that drifts from the code is worse than no contract: an agent that trusts it will
 * confidently do the wrong thing.
 *
 * Phase 9 demonstrated exactly that failure with the codec's hardcoded relation
 * list — `part-of` was registered and silently unserialized. Deriving this file from
 * the same registries is the guard against repeating it in prose.
 *
 * Derived state (ADR-0029): safe to delete, rebuilt by `reindex`, and carrying no
 * generation timestamp so regeneration is idempotent.
 */

import { getRelation, relationKinds } from '../core/relations.js';
import { getGuardrail, type GuardrailConfig } from '../policy/guardrails.js';
import { operations } from '../policy/operations.js';
import type { Skill } from '../policy/skill-schema.js';
import { invocationName, skillTargets } from './adapters.js';
import { getStructure, RAW, type StructureDef } from '../policy/structures.js';

export function generateAgentsMd(
  config: GuardrailConfig,
  structureId = 'default',
  skills: Skill[] = [],
): string {
  const def: StructureDef | undefined = getStructure(structureId);
  const lines = [
    '<!-- GENERATED by engram reindex. Do not edit; edits are lost on regeneration. -->',
    '<!-- Derived state (ADR-0029): safe to delete. On conflict, regenerate — never merge. -->',
    '',
    '# AGENTS.md',
    '',
    'This is an **engram vault**: plain markdown with OKF frontmatter, no database,',
    'no server, no account. Everything here works with `cat`, `rg`, git and Obsidian',
    'whether or not engram is installed.',
    '',
    '## Operations',
    '',
    '| Command | What it does |',
    '|---|---|',
    ...operations().map((op) => `| \`${op.command}\` | ${op.does} |`),
    '',
    '**Capture never rejects.** If you cannot format something now — no time, no',
    'structure, half a thought — capture it. Losing a thought is the only real',
    'failure; an unfiled note is not.',
    '',
    ...howToRun(skills),
    ...whereToFile(def),
    '## You author the relations, not engram',
    '',
    'Engram makes no network calls and runs no model. It cannot infer a relationship.',
    'When you write content you already know how it relates to what exists, so say so',
    'at write time via `format` — that is the moment the information is cheapest and',
    'most reliable.',
    '',
    'A wrong relation is plain text in frontmatter and costs seconds to fix. That is',
    'the design: repair is trivial, so extraction does not have to be perfect.',
    '',
    '## Closed relations',
    '',
    'These carry meaning engram acts on. **Anything else is free association** — it',
    'is recorded and readable, but carries no validity semantics.',
    '',
    '| Relation | Means | Invalidates the target? |',
    '|---|---|---|',
  ];

  for (const name of relationKinds()) {
    const kind = getRelation(name)!;
    lines.push(`| \`${name}\` | ${kind.meaning} | ${kind.invalidatesTarget ? '**yes**' : 'no'} |`);
  }

  lines.push(
    '',
    '## Guardrails in force',
    '',
    'Each is checked at the write gate **and** scanned for by `doctor`. The second',
    'half matters: engram sees only the writes that go through it, and Obsidian or a',
    'shell can write directly.',
    '',
  );

  if (config.enabled.length === 0) {
    lines.push('_None enabled._', '');
  } else {
    lines.push('| Rule | Prevents |', '|---|---|');
    for (const name of config.enabled) {
      const rule = getGuardrail(name);
      if (rule !== undefined) lines.push(`| \`${name}\` | ${rule.prevents} |`);
    }
    lines.push('');
  }

  if (config.pathScope !== undefined) {
    lines.push(
      `**Path scope:** writes are permitted only under \`${config.pathScope.join('`, `')}\`.`,
      '',
    );
  }
  if (config.proposeOnly !== undefined && config.proposeOnly.length > 0) {
    lines.push(`**Propose-only:** \`${config.proposeOnly.join('`, `')}\` need human review.`, '');
  }
  if (config.rateLimit !== undefined) {
    lines.push(`**Rate limit:** at most ${config.rateLimit} new nodes per run.`, '');
  }

  lines.push(
    '## Conventions',
    '',
    '- `index.md` and everything under `views/` are **generated**. Do not edit them.',
    '- Identity is the `id` slug in frontmatter. The path is an address — moving a',
    '  file is cheap because `aliases` records where it used to live.',
    '- A node **may be empty**. A link to an unwritten note is a valid node, not an error.',
    '- A directory with its own `.engram/` is a separate vault. Engram will not read',
    '  into it, and neither should you.',
    '',
  );

  return lines.join('\n');
}

/**
 * Where to file a formatted note.
 *
 * This section is the reason a vault declares a structure at all. Without it two
 * agents working the same vault invent different containers for the same kind of
 * note — observed, not hypothetical: four filings produced `concepts/`,
 * `knowledge/` and `notes/`.
 *
 * Rendered from the vault's own declaration, so engram states a convention
 * without holding an opinion about which one.
 */
function whereToFile(def: StructureDef | undefined): string[] {
  const head = [
    '## Where to file what',
    '',
    `This vault declares the **${def?.label ?? 'default'}** structure. Use these`,
    'containers so filing stays consistent across sessions and across agents.',
    '',
  ];

  if (def === undefined || def.containers.length === 0) {
    return [
      ...head.slice(0, 2),
      'This vault declares **custom**: it has no preset convention.',
      '',
      '**Ask the human where a note belongs, or follow the shape already in the',
      'vault. Do not invent a new top-level folder.** `STRUCTURE.md` is where the',
      'human records their own convention; read it before filing.',
      '',
      `Only \`${RAW.name}/\` is guaranteed to exist: ${RAW.holds}`,
      '',
    ];
  }

  return [
    ...head,
    '| Container | What belongs here |',
    '|---|---|',
    ...[RAW, ...def.containers].map((c) => `| \`${c.name}\` | ${c.holds} |`),
    '',
    'Pass it as `--container <name>`; the directory is used verbatim, so a vault',
    'with `Daily Notes/` keeps that capitalisation. **A new subfolder is fine** —',
    'the path is an address and the slug is the identity, so nothing breaks. Prefer',
    'subdividing an existing container over adding a top-level one.',
    '',
    '`STRUCTURE.md` explains the reasoning and how this scales. Read it once.',
    '',
  ];
}

/**
 * How to actually invoke an operation.
 *
 * **This section is the whole reason FEAT-009 existed.** The contract listed
 * `engram capture [text]` in a table and never said whether that was a shell command,
 * a CLI subcommand or an MCP tool — so an agent was told what engram can do and never
 * told how to ask for it. A capability an agent cannot reach is not a capability.
 */
function howToRun(skills: Skill[]): string[] {
  const targets = skillTargets();
  const mine = skills.filter((s) => s.origin === 'vault');

  const lines = [
    '## How to run these',
    '',
    '`engram` is a **command-line tool**. There is no server to start and no',
    'connection to make. Run it in a shell:',
    '',
    '```bash',
    'engram capture "a thought"',
    'engram doctor',
    '```',
    '',
    'It finds the vault root by looking for `.engram/` in the current directory and',
    'every directory above it, so it works from anywhere inside the vault. Outside one,',
    'it says so rather than creating a vault where you happen to be standing.',
    '',
    '### As slash commands',
    '',
    'Every operation is also a skill, so it can be invoked directly with no MCP server:',
    '',
    '| Agent | Operations | Skills you wrote |',
    '|---|---|---|',
  ];

  for (const agent of targets) {
    const ops = `\`${invocationName(agent.skills, 'format', true)}\`, \`${invocationName(
      agent.skills,
      'capture',
      true,
    )}\`, …`;
    const yours =
      mine.length === 0
        ? '_none yet_'
        : mine.map((s) => `\`${invocationName(agent.skills, s.name, false)}\``).join(', ');
    lines.push(`| ${agent.name} | ${ops} | ${yours} |`);
  }

  lines.push(
    '',
    "**If it carries engram's mark, engram wrote it. If it does not, you did.** Only the",
    'separator changes between agents — `:` where the host namespaces, `-` where it',
    'does not.',
    '',
  );

  const caveats = targets.flatMap((a) => a.skills.caveats.map((c) => `- **${a.name}**: ${c}`));
  if (caveats.length > 0) {
    lines.push('Worth knowing:', '', ...caveats, '');
  }

  lines.push(
    '### Over MCP',
    '',
    'Optional, and additive. `engram mcp` serves the same operations over stdio for a',
    'client configured to spawn it. Nothing listens on a socket unless you pass',
    '`--http` (ADR-0041), and **approving a queued proposal is never an MCP tool** —',
    'an agent that could approve its own proposal would have turned a refusal into a',
    'retry (ADR-0042).',
    '',
    '### Skills are generated; the source is `engram/skills/`',
    '',
    "Everything in an agent's own skills directory is **derived state** — regenerated",
    'by `engram reindex` and overwritten without warning. To change a skill, edit',
    '`engram/skills/<name>/SKILL.md` and reindex. To add one, use `engram skill new',
    '<name>` or the `create-skill` skill.',
    '',
  );
  return lines;
}
