/**
 * `AGENTS.md` — the entry contract for any agent working in this vault (ADR-0011).
 *
 * **Generated, never hand-written.** It names the operations, the guardrails
 * actually in force, and the closed relation set read from the registry. A contract
 * that drifts from the code is worse than no contract: an agent that trusts it will
 * confidently do the wrong thing.
 *
 * Phase 9 demonstrated exactly that failure with the codec's hardcoded relation
 * list — `part-of` was registered and silently unserialized. Deriving this file from
 * the same registries is the guard against repeating it in prose.
 *
 * Derived state (ADR-0029): safe to delete, rebuilt by `reindex`, and carrying no
 * generation timestamp so regeneration is idempotent.
 */

import { getRelation, relationKinds } from '../core/relations.js';
import { getGuardrail, type GuardrailConfig } from '../policy/guardrails.js';

const OPERATIONS = [
  ['`engram init`', 'scaffold a vault. Non-destructive; never overwrites.'],
  ['`engram capture [text]`', '**persist raw content. Never validates, never fails.**'],
  ['`engram format`', 'content + your structure → validated nodes and relations.'],
  ['`engram link <file> <to> <kind>`', 'assert one typed relation.'],
  ['`engram reindex`', 'regenerate derived state. Idempotent.'],
  ['`engram doctor`', 'health and integrity report. Read-only.'],
] as const;

export function generateAgentsMd(config: GuardrailConfig): string {
  const lines = [
    '<!-- GENERATED by engram reindex. Do not edit; edits are lost on regeneration. -->',
    '<!-- Derived state (ADR-0029): safe to delete. On conflict, regenerate — never merge. -->',
    '',
    '# AGENTS.md',
    '',
    'This is an **engram vault**: plain markdown with OKF frontmatter, no database,',
    'no server, no account. Everything here works with `cat`, `rg`, git and Obsidian',
    'whether or not engram is installed.',
    '',
    '## Operations',
    '',
    '| Command | What it does |',
    '|---|---|',
    ...OPERATIONS.map(([cmd, desc]) => `| ${cmd} | ${desc} |`),
    '',
    '**Capture never rejects.** If you cannot format something now — no time, no',
    'structure, half a thought — capture it. Losing a thought is the only real',
    'failure; an unfiled note is not.',
    '',
    '## You author the relations, not engram',
    '',
    'Engram makes no network calls and runs no model. It cannot infer a relationship.',
    'When you write content you already know how it relates to what exists, so say so',
    'at write time via `format` — that is the moment the information is cheapest and',
    'most reliable.',
    '',
    'A wrong relation is plain text in frontmatter and costs seconds to fix. That is',
    'the design: repair is trivial, so extraction does not have to be perfect.',
    '',
    '## Closed relations',
    '',
    'These carry meaning engram acts on. **Anything else is free association** — it',
    'is recorded and readable, but carries no validity semantics.',
    '',
    '| Relation | Means | Invalidates the target? |',
    '|---|---|---|',
  ];

  for (const name of relationKinds()) {
    const kind = getRelation(name)!;
    lines.push(`| \`${name}\` | ${kind.meaning} | ${kind.invalidatesTarget ? '**yes**' : 'no'} |`);
  }

  lines.push(
    '',
    '## Guardrails in force',
    '',
    'Each is checked at the write gate **and** scanned for by `doctor`. The second',
    'half matters: engram sees only the writes that go through it, and Obsidian or a',
    'shell can write directly.',
    '',
  );

  if (config.enabled.length === 0) {
    lines.push('_None enabled._', '');
  } else {
    lines.push('| Rule | Prevents |', '|---|---|');
    for (const name of config.enabled) {
      const rule = getGuardrail(name);
      if (rule !== undefined) lines.push(`| \`${name}\` | ${rule.prevents} |`);
    }
    lines.push('');
  }

  if (config.pathScope !== undefined) {
    lines.push(
      `**Path scope:** writes are permitted only under \`${config.pathScope.join('`, `')}\`.`,
      '',
    );
  }
  if (config.proposeOnly !== undefined && config.proposeOnly.length > 0) {
    lines.push(`**Propose-only:** \`${config.proposeOnly.join('`, `')}\` need human review.`, '');
  }
  if (config.rateLimit !== undefined) {
    lines.push(`**Rate limit:** at most ${config.rateLimit} new nodes per run.`, '');
  }

  lines.push(
    '## Conventions',
    '',
    '- `index.md` and everything under `views/` are **generated**. Do not edit them.',
    '- Identity is the `id` slug in frontmatter. The path is an address — moving a',
    '  file is cheap because `aliases` records where it used to live.',
    '- A node **may be empty**. A link to an unwritten note is a valid node, not an error.',
    '- A directory with its own `.engram/` is a separate vault. Engram will not read',
    '  into it, and neither should you.',
    '',
  );

  return lines.join('\n');
}
