/**
 * Render every discovered skill into every agent's own directory.
 *
 * **The same argument as ADR-0017, applied to skills.** Each agent reads only its
 * own location, and a pointer to somewhere else is a contract the agent never
 * receives. So each gets a full copy, and the duplication is safe because there is
 * exactly one generator (`serializeSkill`) and every copy is rewritten by `reindex`.
 * No copy is more real than another, so no copy can fall behind.
 *
 * ## What is engram's and what is yours
 *
 * `engram/skills/` is **source** — yours, visible in Obsidian, committed. Everything
 * written here is a **render target**: derived state under ADR-0029, regenerated,
 * and never the thing you edit.
 *
 * The rule a reader has to remember is one sentence: **if it carries engram's mark,
 * engram wrote it.** `/engram:format` where the host namespaces for us,
 * `/engram-format` where it does not, and `/your-own-name` always unmarked.
 *
 * ## Why there is no lock on engram's own skills
 *
 * Because engram's premise is plain files you own, and a tool that says that and
 * then chmods your files is lying about one of the two. The protection is
 * regeneration: edit a rendered skill and `reindex` takes the edit back, exactly as
 * it does for `index.md`. What makes that acceptable is that **nobody ever needs to
 * edit engram's copy** — overriding by name replaces it wholesale from a file that
 * is yours.
 */

import type { FileStore } from '../core/ports.js';
import { yamlScalar } from '../format/registry.js';
import {
  getOperation,
  OPERATION_TOOLS,
  operations,
  type OperationDef,
} from '../policy/operations.js';
import { managedBy, serializeSkill, SKILLS_DIR } from '../policy/skills.js';
import { META, SKILL_FILE, type Skill } from '../policy/skill-schema.js';
import { VERSION } from '../version.js';
import {
  AGENTS,
  commandPath,
  commandTargets,
  isCommandPath,
  PLUGIN_MANIFEST,
  PLUGIN_MANIFEST_DIR,
  skillPath,
  skillTargets,
  type AgentDescriptor,
  type SkillTarget,
} from './adapters.js';

export interface SkillRenderResult {
  /** Files engram wrote or rewrote. */
  written: string[];
  /**
   * Present, and **not** engram's to touch — no provenance marker.
   *
   * Reported rather than overwritten. A skill someone else put in the same directory
   * is theirs, and the marker is the only thing that distinguishes it from ours.
   */
  skipped: { path: string; why: string }[];
  /**
   * Engram-managed renders that no current skill maps to any more.
   *
   * Almost always the leftover copy of a built-in you have since overridden. The
   * `FileStore` port has four methods and removal is deliberately not one of them —
   * the same instinct as the `no-delete` guardrail and as `upgrade`, which copies and
   * then tells you what to remove. So these are reported with the command, never
   * deleted behind your back.
   */
  stale: string[];
}

/**
 * The plugin manifest.
 *
 * `version` is engram's own, so a rendered plugin says which engram wrote it, and
 * `description`/`author` are present because the official validator asks for all
 * three. Only `name` is strictly required.
 */
export function pluginManifest(name: string, version = VERSION): string {
  return `${JSON.stringify(
    {
      name,
      description:
        "engram's own skills — the six operations, plus the skills it ships. " +
        'Generated by `engram reindex`; edit engram/skills/ instead.',
      version,
      author: { name: 'engram' },
    },
    null,
    2,
  )}\n`;
}

/**
 * The content of one rendered **command**.
 *
 * **One definition**, like `renderOne`: the renderer and the audit both call it,
 * so `doctor` cannot grow its own opinion of what a rendered command is. The body
 * embeds the same registry instructions the operation's SKILL.md carries — never a
 * hand-written variant — plus `$ARGUMENTS`, so `/engram-capture some thought`
 * passes the thought through on the first try.
 */
export function renderCommand(def: OperationDef, version = VERSION): string {
  const body = [
    '---',
    // opencode reads this one frontmatter field; everything engram-specific sits
    // under metadata, which hosts ignore.
    `description: ${yamlScalar(def.does.replace(/\*\*/g, ''))}`,
    'metadata:',
    `  ${META.managed}: ${yamlScalar(version)}`,
    '---',
    '',
    '<!-- Generated by `engram reindex` from the operation registry. Commands have',
    `     no user-editable source; regenerate rather than edit (ADR-0029). -->`,
    '',
    `Run the engram \`${def.name}\` operation on this vault.`,
    '',
    '# What it does',
    '',
    def.does.replace(/\*\*/g, ''),
    '',
    '# How to run it',
    '',
    '```bash',
    def.command,
    '```',
    '',
    'Run it in the vault root, in a shell.',
    '',
    '# Steps',
    '',
    ...def.steps,
    '',
    '# Arguments',
    '',
    'The user passed these arguments with the command, if any:',
    '',
    '$ARGUMENTS',
  ];
  return `${body.join('\n')}\n`;
}

export interface CommandRenderResult {
  /** Command files engram wrote or rewrote. */
  written: string[];
  /**
   * Present, and not engram's to touch — no provenance marker. The skill rule:
   * someone else's file at our destination is theirs, reported and left alone.
   */
  skipped: { path: string; why: string }[];
  /** Engram-managed renders no current operation maps to any more. Reported, never deleted. */
  stale: string[];
}

/**
 * Write every operation's command into every agent that has a verified directory.
 *
 * Mirrors `renderSkills` exactly — same skip rule, same stale sweep, same shape —
 * because the semantics are the same contract in a second file type.
 */
export async function renderCommands(
  files: FileStore,
  agents: AgentDescriptor[] = AGENTS,
  version = VERSION,
): Promise<CommandRenderResult> {
  const written: string[] = [];
  const skipped: CommandRenderResult['skipped'] = [];
  const stale: string[] = [];

  for (const agent of commandTargets(agents)) {
    const dir = agent.commands.dir;
    const ours = new Set<string>();

    for (const def of operations()) {
      const path = commandPath(agent.commands, def.name);
      ours.add(path);

      const existing = await files.read(path);
      if (existing !== null && managedBy(existing) === null) {
        skipped.push({
          path,
          why: 'not written by engram — no provenance marker. Left exactly as it is.',
        });
        continue;
      }

      await files.write(path, renderCommand(def, version));
      written.push(path);
    }

    // Anything engram wrote here before and no longer maps to an operation.
    for (const path of await files.list()) {
      if (!path.startsWith(`${dir}/`) || ours.has(path)) continue;
      if (!path.endsWith('.md')) continue;
      const raw = await files.read(path);
      if (raw !== null && managedBy(raw) !== null) stale.push(path);
    }
  }

  return { written: written.sort(), skipped, stale: stale.sort() };
}

/** The name written to frontmatter, which the standard requires to match the directory. */
function renderedName(target: SkillTarget, name: string, managed: boolean): string {
  if (!managed) return name;
  return target.plugin === null ? `engram-${name}` : name;
}

/** Where the reader should go to change this skill for real. */
function sourceOf(skill: Skill): string {
  return skill.origin === 'vault'
    ? `${SKILLS_DIR}/${skill.name}/${SKILL_FILE}`.replace(/^\//, '')
    : `engram itself — create ${SKILLS_DIR.replace(/^\//, '')}/${skill.name}/${SKILL_FILE} to replace it`;
}

/**
 * The content of one rendered skill.
 *
 * **One definition.** The writer and the read-only audit both call it, so `doctor`
 * cannot develop its own opinion of what a rendered skill should look like and start
 * reporting differences that are its own. This project has been bitten twice by two
 * places describing the same thing.
 */
function renderOne(target: SkillTarget, skill: Skill, managed: boolean, version: string): string {
  return serializeSkill(skill, {
    name: renderedName(target, skill.name, managed),
    managed: version,
    source: sourceOf(skill),
    // Only engram's own operation skills carry the hint. A skill you wrote that
    // happens to share a name is yours, and engram does not restrict it.
    ...(managed && getOperation(skill.name) !== undefined ? { allowedTools: OPERATION_TOOLS } : {}),
  });
}

/**
 * Write every skill into every agent that has a verified directory.
 *
 * An agent with no `skills` target gets nothing, which is the honest outcome: engram
 * will not write files into a directory it has not confirmed is read (ADR-0044).
 */
export async function renderSkills(
  files: FileStore,
  skills: Skill[],
  agents: AgentDescriptor[] = AGENTS,
  version = VERSION,
): Promise<SkillRenderResult> {
  const written: string[] = [];
  const skipped: SkillRenderResult['skipped'] = [];
  const stale: string[] = [];

  for (const agent of skillTargets(agents)) {
    const target = agent.skills;
    const ours = new Set<string>();

    if (target.plugin !== null) {
      const manifest = `${target.dir}/${target.plugin}/${PLUGIN_MANIFEST_DIR}/${PLUGIN_MANIFEST}`;
      await files.write(manifest, pluginManifest(target.plugin, version));
      written.push(manifest);
      ours.add(manifest);
    }

    for (const skill of skills) {
      const managed = skill.origin === 'built-in';
      const path = skillPath(target, skill.name, managed);
      ours.add(path);

      // A file already there without the marker is not engram's. Never touched,
      // and reported — this is the contract splice's rule in a different shape.
      const existing = await files.read(path);
      if (existing !== null && managedBy(existing) === null) {
        skipped.push({
          path,
          why: 'not written by engram — no provenance marker. Left exactly as it is.',
        });
        continue;
      }

      await files.write(path, renderOne(target, skill, managed, version));
      written.push(path);
    }

    // Anything engram wrote here before and no longer maps to a skill.
    for (const path of await files.list()) {
      if (!path.startsWith(`${target.dir}/`) || ours.has(path)) continue;
      if (!path.endsWith(`/${SKILL_FILE}`)) continue;
      const raw = await files.read(path);
      if (raw !== null && managedBy(raw) !== null) stale.push(path);
    }
  }

  return { written: written.sort(), skipped, stale: stale.sort() };
}

export const BEGIN_IGNORE = '# BEGIN engram — rendered skills, regenerate with `engram reindex`';
export const END_IGNORE = '# END engram';

/**
 * The gitignore lines engram manages for its render targets.
 *
 * **Narrow on purpose.** `.claude/` also holds settings, commands and skills the user
 * wrote themselves; ignoring the whole directory would quietly stop those being
 * committed. Engram ignores a plugin directory it wholly owns, and otherwise names
 * each rendered directory — so what is ignored is exactly what is generated.
 */
export function skillIgnoreLines(skills: Skill[], agents: AgentDescriptor[] = AGENTS): string[] {
  const lines: string[] = [];
  for (const agent of skillTargets(agents)) {
    const target = agent.skills;
    if (target.plugin !== null) {
      lines.push(`${target.dir}/${target.plugin}/`);
      for (const s of skills.filter((s) => s.origin === 'vault')) {
        lines.push(`${target.dir}/${s.name}/`);
      }
      continue;
    }
    for (const s of skills) {
      lines.push(`${target.dir}/${renderedName(target, s.name, s.origin === 'built-in')}/`);
    }
  }
  // Commands are derived state too. Only the managed prefix is ignored — the rest
  // of a commands directory may hold the user's own commands, which are theirs to
  // commit.
  for (const agent of commandTargets(agents)) {
    lines.push(`${agent.commands.dir}/engram-*.md`);
  }
  return [...new Set(lines)].sort();
}

/**
 * Splice the managed ignore block into `.gitignore`, preserving everything else.
 *
 * Delimited exactly like the contract block, and for the same reason: engram owns
 * what is between the markers and nothing else.
 */
export function spliceIgnore(existing: string, lines: string[]): string {
  const block = [BEGIN_IGNORE, ...lines, END_IGNORE].join('\n');
  const start = existing.indexOf(BEGIN_IGNORE);
  const end = existing.indexOf(END_IGNORE);
  if (start !== -1 && end !== -1 && end > start) {
    return `${existing.slice(0, start)}${block}${existing.slice(end + END_IGNORE.length)}`;
  }
  return existing.trim() === '' ? `${block}\n` : `${existing.trimEnd()}\n\n${block}\n`;
}

export interface SkillAudit {
  /** Engram-managed renders no current skill maps to. Usually an overridden built-in. */
  stale: string[];
  /**
   * Rendered by **this** engram, and since changed by hand.
   *
   * Worth saying because the change is about to be lost and nothing else would
   * mention it. Distinguished from a copy written by an older engram — that differs
   * too, but it needs a reindex rather than a warning about editing.
   */
  edited: string[];
  /** A skill in the source that has not been rendered anywhere. */
  unrendered: string[];
  /** A file where engram's render should be, that engram did not write and will not touch. */
  foreign: string[];
}

/**
 * The read-only half of rendering, for `doctor`.
 *
 * Separate from `renderSkills` because `doctor` changes nothing — that is the whole
 * shape of the command (ADR-0028 makes not-acting engram's default posture, and
 * `--fix` its single deliberate exception). Sharing `skillPath` with the renderer is
 * what keeps the two from disagreeing about where a skill belongs.
 */
export async function auditSkills(
  files: FileStore,
  skills: Skill[],
  agents: AgentDescriptor[] = AGENTS,
  version = VERSION,
): Promise<SkillAudit> {
  // Holds the content engram *would* write, so the audit can tell "missing" from
  // "changed by hand" without a second definition of how a skill is rendered.
  // Commands join the same expected-map, so one definition covers both file types.
  const expected = new Map<string, string>();
  for (const agent of skillTargets(agents)) {
    for (const skill of skills) {
      const managed = skill.origin === 'built-in';
      expected.set(
        skillPath(agent.skills, skill.name, managed),
        renderOne(agent.skills, skill, managed, version),
      );
    }
  }
  for (const agent of commandTargets(agents)) {
    for (const def of operations()) {
      expected.set(commandPath(agent.commands, def.name), renderCommand(def, version));
    }
  }

  const stale: string[] = [];
  const foreign: string[] = [];
  const edited: string[] = [];
  const present = new Set<string>();

  for (const path of await files.list()) {
    const inSkillArea =
      path.endsWith(`/${SKILL_FILE}`) &&
      skillTargets(agents).some((a) => path.startsWith(`${a.skills.dir}/`));
    const inCommandArea = path.endsWith('.md') && isCommandPath(path, agents);
    if (!inSkillArea && !inCommandArea) continue;
    const raw = await files.read(path);
    const managed = raw === null ? null : managedBy(raw);
    if (managed !== null) present.add(path);
    if (managed !== null && !expected.has(path)) stale.push(path);
    if (managed === null && expected.has(path)) foreign.push(path);
    // Only when the marker says *this* version wrote it. A copy from an older engram
    // differs for a reason that has nothing to do with editing, and reporting it as
    // a hand edit would be both wrong and the sort of warning people learn to ignore.
    if (managed === version && raw !== expected.get(path)) edited.push(path);
  }

  const unrendered = [...expected.keys()].filter((p) => !present.has(p) && !foreign.includes(p));
  return {
    stale: stale.sort(),
    unrendered: unrendered.sort(),
    foreign: foreign.sort(),
    edited: edited.sort(),
  };
}
