/**
 * Render every discovered skill into every agent's own directory.
 *
 * **The same argument as ADR-0017, applied to skills.** Each agent reads only its
 * own location, and a pointer to somewhere else is a contract the agent never
 * receives. So each gets a full copy, and the duplication is safe because there is
 * exactly one generator (`serializeSkill`) and every copy is rewritten by `reindex`.
 * No copy is more real than another, so no copy can fall behind.
 *
 * ## What is engram's and what is yours
 *
 * `engram/skills/` is **source** — yours, visible in Obsidian, committed. Everything
 * written here is a **render target**: derived state under ADR-0029, regenerated,
 * and never the thing you edit.
 *
 * The rule a reader has to remember is one sentence: **if it carries engram's mark,
 * engram wrote it.** `/engram:format` where the host namespaces for us,
 * `/engram-format` where it does not, and `/your-own-name` always unmarked.
 *
 * ## Why there is no lock on engram's own skills
 *
 * Because engram's premise is plain files you own, and a tool that says that and
 * then chmods your files is lying about one of the two. The protection is
 * regeneration: edit a rendered skill and `reindex` takes the edit back, exactly as
 * it does for `index.md`. What makes that acceptable is that **nobody ever needs to
 * edit engram's copy** — overriding by name replaces it wholesale from a file that
 * is yours.
 */

import type { FileStore } from '../core/ports.js';
import { getOperation, OPERATION_TOOLS } from '../policy/operations.js';
import { managedBy, serializeSkill, SKILLS_DIR } from '../policy/skills.js';
import { SKILL_FILE, type Skill } from '../policy/skill-schema.js';
import { VERSION } from '../version.js';
import {
  AGENTS,
  PLUGIN_MANIFEST,
  PLUGIN_MANIFEST_DIR,
  skillPath,
  skillTargets,
  type AgentDescriptor,
  type SkillTarget,
} from './adapters.js';

export interface SkillRenderResult {
  /** Files engram wrote or rewrote. */
  written: string[];
  /**
   * Present, and **not** engram's to touch — no provenance marker.
   *
   * Reported rather than overwritten. A skill someone else put in the same directory
   * is theirs, and the marker is the only thing that distinguishes it from ours.
   */
  skipped: { path: string; why: string }[];
  /**
   * Engram-managed renders that no current skill maps to any more.
   *
   * Almost always the leftover copy of a built-in you have since overridden. The
   * `FileStore` port has four methods and removal is deliberately not one of them —
   * the same instinct as the `no-delete` guardrail and as `upgrade`, which copies and
   * then tells you what to remove. So these are reported with the command, never
   * deleted behind your back.
   */
  stale: string[];
}

/**
 * The plugin manifest.
 *
 * `version` is engram's own, so a rendered plugin says which engram wrote it, and
 * `description`/`author` are present because the official validator asks for all
 * three. Only `name` is strictly required.
 */
export function pluginManifest(name: string, version = VERSION): string {
  return `${JSON.stringify(
    {
      name,
      description:
        "engram's own skills — the six operations, plus the skills it ships. " +
        'Generated by `engram reindex`; edit engram/skills/ instead.',
      version,
      author: { name: 'engram' },
    },
    null,
    2,
  )}\n`;
}

/** The name written to frontmatter, which the standard requires to match the directory. */
function renderedName(target: SkillTarget, name: string, managed: boolean): string {
  if (!managed) return name;
  return target.plugin === null ? `engram-${name}` : name;
}

/** Where the reader should go to change this skill for real. */
function sourceOf(skill: Skill): string {
  return skill.origin === 'vault'
    ? `${SKILLS_DIR}/${skill.name}/${SKILL_FILE}`.replace(/^\//, '')
    : `engram itself — create ${SKILLS_DIR.replace(/^\//, '')}/${skill.name}/${SKILL_FILE} to replace it`;
}

/**
 * Write every skill into every agent that has a verified directory.
 *
 * An agent with no `skills` target gets nothing, which is the honest outcome: engram
 * will not write files into a directory it has not confirmed is read (ADR-0044).
 */
export async function renderSkills(
  files: FileStore,
  skills: Skill[],
  agents: AgentDescriptor[] = AGENTS,
  version = VERSION,
): Promise<SkillRenderResult> {
  const written: string[] = [];
  const skipped: SkillRenderResult['skipped'] = [];
  const stale: string[] = [];

  for (const agent of skillTargets(agents)) {
    const target = agent.skills;
    const ours = new Set<string>();

    if (target.plugin !== null) {
      const manifest = `${target.dir}/${target.plugin}/${PLUGIN_MANIFEST_DIR}/${PLUGIN_MANIFEST}`;
      await files.write(manifest, pluginManifest(target.plugin, version));
      written.push(manifest);
      ours.add(manifest);
    }

    for (const skill of skills) {
      const managed = skill.origin === 'built-in';
      const path = skillPath(target, skill.name, managed);
      ours.add(path);

      // A file already there without the marker is not engram's. Never touched,
      // and reported — this is the contract splice's rule in a different shape.
      const existing = await files.read(path);
      if (existing !== null && managedBy(existing) === null) {
        skipped.push({
          path,
          why: 'not written by engram — no provenance marker. Left exactly as it is.',
        });
        continue;
      }

      await files.write(
        path,
        serializeSkill(skill, {
          name: renderedName(target, skill.name, managed),
          managed: version,
          source: sourceOf(skill),
          // Only engram's own operation skills carry the hint. A skill you wrote that
          // happens to share a name is yours, and engram does not restrict it.
          ...(managed && getOperation(skill.name) !== undefined
            ? { allowedTools: OPERATION_TOOLS }
            : {}),
        }),
      );
      written.push(path);
    }

    // Anything engram wrote here before and no longer maps to a skill.
    for (const path of await files.list()) {
      if (!path.startsWith(`${target.dir}/`) || ours.has(path)) continue;
      if (!path.endsWith(`/${SKILL_FILE}`)) continue;
      const raw = await files.read(path);
      if (raw !== null && managedBy(raw) !== null) stale.push(path);
    }
  }

  return { written: written.sort(), skipped, stale: stale.sort() };
}

export const BEGIN_IGNORE = '# BEGIN engram — rendered skills, regenerate with `engram reindex`';
export const END_IGNORE = '# END engram';

/**
 * The gitignore lines engram manages for its render targets.
 *
 * **Narrow on purpose.** `.claude/` also holds settings, commands and skills the user
 * wrote themselves; ignoring the whole directory would quietly stop those being
 * committed. Engram ignores a plugin directory it wholly owns, and otherwise names
 * each rendered directory — so what is ignored is exactly what is generated.
 */
export function skillIgnoreLines(skills: Skill[], agents: AgentDescriptor[] = AGENTS): string[] {
  const lines: string[] = [];
  for (const agent of skillTargets(agents)) {
    const target = agent.skills;
    if (target.plugin !== null) {
      lines.push(`${target.dir}/${target.plugin}/`);
      for (const s of skills.filter((s) => s.origin === 'vault')) {
        lines.push(`${target.dir}/${s.name}/`);
      }
      continue;
    }
    for (const s of skills) {
      lines.push(`${target.dir}/${renderedName(target, s.name, s.origin === 'built-in')}/`);
    }
  }
  return [...new Set(lines)].sort();
}

/**
 * Splice the managed ignore block into `.gitignore`, preserving everything else.
 *
 * Delimited exactly like the contract block, and for the same reason: engram owns
 * what is between the markers and nothing else.
 */
export function spliceIgnore(existing: string, lines: string[]): string {
  const block = [BEGIN_IGNORE, ...lines, END_IGNORE].join('\n');
  const start = existing.indexOf(BEGIN_IGNORE);
  const end = existing.indexOf(END_IGNORE);
  if (start !== -1 && end !== -1 && end > start) {
    return `${existing.slice(0, start)}${block}${existing.slice(end + END_IGNORE.length)}`;
  }
  return existing.trim() === '' ? `${block}\n` : `${existing.trimEnd()}\n\n${block}\n`;
}
