import { describe, expect, it } from 'vitest';
import { makeEdge, makeNode, type AssertionStamp } from '../../src/core/model.js';
import {
  generateAll,
  generateIndex,
  generateOrphans,
  generateRecent,
  generateSuperseded,
} from '../../src/views/generate.js';

const NOW = '2026-08-12T09:00:00.000Z';
const stamp = (over: Partial<AssertionStamp> = {}): AssertionStamp => ({
  by: 'avinash',
  at: '2026-01-01T00:00:00.000Z',
  until: null,
  ...over,
});
const node = (id: string, over: Partial<AssertionStamp> = {}) =>
  makeNode({ id, path: `/${id}.md`, stamp: stamp(over) });
const edge = (from: string, to: string, kind: string) =>
  makeEdge({ from, to, kind, stamp: stamp() });

/**
 * The constraint that makes `reindex` idempotent, and therefore makes ADR-0029's
 * "regenerate, never merge" quiet rather than a permanent source of diffs.
 */
describe('no generated file embeds a generation timestamp', () => {
  const nodes = [node('a'), node('b')];
  const edges = [edge('a', 'b', 'part-of')];

  it('generating twice produces byte-identical output', () => {
    const first = generateAll(nodes, edges, NOW);
    const second = generateAll(nodes, edges, '2027-12-31T23:59:59.000Z');
    expect(second.map((f) => f.content)).toEqual(first.map((f) => f.content));
  });

  it('no generated content contains the current wall-clock year', () => {
    const year = String(new Date().getFullYear());
    for (const f of generateAll(nodes, edges, NOW)) {
      const generatedLines = f.content.split('\n').filter((l) => !l.includes('2026-01-01'));
      expect(generatedLines.join('\n')).not.toContain(`Generated at ${year}`);
    }
  });

  it('every generated file says it is generated and safe to delete', () => {
    for (const f of generateAll(nodes, edges, NOW)) {
      expect(f.content).toContain('GENERATED by engram reindex');
      expect(f.content).toContain('regenerate — never merge');
    }
  });
});

describe('index.md — the structure tree projected from part-of', () => {
  it('groups nodes under their container', () => {
    const { content } = generateIndex(
      [node('raft'), node('paxos')],
      [edge('raft', 'consensus', 'part-of'), edge('paxos', 'consensus', 'part-of')],
    );
    expect(content).toContain('## consensus');
    expect(content).toContain('[raft](/raft.md)');
    expect(content).toContain('[paxos](/paxos.md)');
  });

  it('lists nodes with no container under Unfiled', () => {
    const { content } = generateIndex([node('loose')], []);
    expect(content).toContain('## Unfiled');
    expect(content).toContain('[loose](/loose.md)');
  });

  it('percent-encodes spaced paths (BUG-001 stays fixed downstream)', () => {
    const spaced = makeNode({ id: 'x', path: '/My Notes/Five Dimensions.md', stamp: stamp() });
    expect(generateIndex([spaced], []).content).toContain('/My%20Notes/Five%20Dimensions.md');
  });

  it('an empty vault generates a valid file, not a crash', () => {
    expect(generateIndex([], []).content).toContain('Nothing here yet');
  });

  it('is deterministic regardless of input order', () => {
    const edges = [edge('a', 'c', 'part-of'), edge('b', 'c', 'part-of')];
    const one = generateIndex([node('a'), node('b')], edges).content;
    const two = generateIndex([node('b'), node('a')], edges).content;
    expect(one).toBe(two);
  });
});

describe('views/superseded.md — what grep cannot tell you is stale', () => {
  it('lists the superseded node and names what replaced it', () => {
    const { content } = generateSuperseded(
      [node('march'), node('june')],
      [edge('june', 'march', 'supersedes')],
    );
    expect(content).toContain('[march](/march.md)');
    expect(content).toContain('superseded by `june`');
    expect(content).not.toContain('[june](/june.md)');
  });

  it('says so plainly when nothing is superseded', () => {
    expect(generateSuperseded([node('a')], []).content).toContain('Nothing is superseded');
  });
});

describe('views/recent.md', () => {
  it('orders most recent first', () => {
    const { content } = generateRecent([
      node('old', { at: '2025-01-01T00:00:00.000Z' }),
      node('new', { at: '2026-06-01T00:00:00.000Z' }),
    ]);
    expect(content.indexOf('[new]')).toBeLessThan(content.indexOf('[old]'));
  });

  it('breaks ties by id so output is deterministic', () => {
    const at = '2026-01-01T00:00:00.000Z';
    const one = generateRecent([node('b', { at }), node('a', { at })]).content;
    const two = generateRecent([node('a', { at }), node('b', { at })]).content;
    expect(one).toBe(two);
  });

  it('caps the list', () => {
    const many = Array.from({ length: 100 }, (_, i) => node(`n${String(i).padStart(3, '0')}`));
    const lines = generateRecent(many, 10)
      .content.split('\n')
      .filter((l) => l.startsWith('- ['));
    expect(lines).toHaveLength(10);
  });
});

describe('views/orphans.md — content nothing points at', () => {
  it('lists nodes with no edges in either direction', () => {
    const { content } = generateOrphans(
      [node('connected'), node('alone'), node('target')],
      [edge('connected', 'target', 'sources')],
    );
    expect(content).toContain('[alone](/alone.md)');
    expect(content).not.toContain('[connected]');
    expect(content).not.toContain('[target]');
  });

  it('says so plainly when nothing is orphaned', () => {
    expect(generateOrphans([node('a'), node('b')], [edge('a', 'b', 'sources')]).content).toContain(
      'Nothing is orphaned',
    );
  });
});

describe('generateAll', () => {
  it('produces exactly the four derived files', () => {
    expect(generateAll([node('a')], [], NOW).map((f) => f.path)).toEqual([
      '/index.md',
      '/views/superseded.md',
      '/views/recent.md',
      '/views/orphans.md',
    ]);
  });

  it('omits expired nodes from the index but keeps them in recent', () => {
    // The index is a live structure tree; recent is a history. Different jobs.
    const lapsed = makeNode({
      id: 'lapsed',
      path: '/lapsed.md',
      stamp: stamp({ until: '2026-01-31T00:00:00.000Z' }),
    });
    const files = generateAll([lapsed], [], NOW);
    expect(files.find((f) => f.path === '/index.md')!.content).not.toContain('[lapsed]');
    expect(files.find((f) => f.path.endsWith('recent.md'))!.content).toContain('[lapsed]');
  });
});

/**
 * ADR-0023: views "provide the *other* arrangements as extra entry points".
 *
 * The format has always allowed a node to declare several parents. The index
 * generator used `.find()` and kept only the first, so one note could never
 * appear in two groupings — the model permitted it and the projection discarded
 * it. This is what makes several structures over the same files possible without
 * moving or duplicating anything.
 */
describe('a node appears under every container it claims', () => {
  const at = '2026-08-22T09:00:00.000Z';
  const stamp = { by: 'me', at, until: null };
  const n = (id: string) => makeNode({ id, path: `/${id}.md`, stamp, body: `# ${id}` });
  const partOf = (from: string, to: string) => makeEdge({ from, to, kind: 'part-of', stamp });

  it('lists it in both places, from one file', () => {
    const { content } = generateIndex(
      [n('raft')],
      [partOf('raft', 'concepts'), partOf('raft', 'consensus')],
    );
    expect(content).toContain('## concepts');
    expect(content).toContain('## consensus');
    expect(content.match(/\/raft\.md/g)).toHaveLength(2);
  });

  it('does not duplicate it when the same edge is asserted twice', () => {
    const { content } = generateIndex(
      [n('raft')],
      [partOf('raft', 'concepts'), partOf('raft', 'concepts')],
    );
    expect(content.match(/\/raft\.md/g)).toHaveLength(1);
  });

  it('still files a node with no parent under Unfiled', () => {
    expect(generateIndex([n('loose')], []).content).toContain('## Unfiled');
  });
});
