/**
 * View generation — projections of edges into alternative entry points (ADR-0023).
 *
 * Views move nothing and duplicate nothing. Every file here is **derived**: safe to
 * delete, rebuilt by `reindex`, gitignored by default (ADR-0029).
 *
 * **No generated file embeds a generation timestamp.** That single constraint is
 * what makes `reindex` idempotent, and therefore what makes ADR-0029's "regenerate,
 * never merge" quiet rather than a permanent source of spurious diffs.
 */

import { isExpired, type Edge, type Instant, type Node } from '../core/model.js';
import { VIEWS_DIR } from '../core/paths.js';
import { encodeLinkTarget } from '../format/links.js';

export interface GeneratedFile {
  path: string;
  content: string;
}

const HEADER = (title: string, note: string): string =>
  [
    `<!-- GENERATED by engram reindex. Do not edit; edits are lost on regeneration. -->`,
    `<!-- Derived state (ADR-0029): safe to delete. On conflict, regenerate — never merge. -->`,
    ``,
    `# ${title}`,
    ``,
    `> ${note}`,
    ``,
  ].join('\n');

const bullet = (n: Node): string => `- [${n.id}](${encodeLinkTarget(n.path)})`;

const emptyNote = (what: string): string => `_Nothing ${what}._\n`;

/** `index.md` — the structure tree, projected from `part-of` edges. */
export function generateIndex(nodes: Node[], edges: Edge[]): GeneratedFile {
  const containers = new Map<string, Node[]>();
  const loose: Node[] = [];

  for (const n of nodes) {
    // **Every** parent, not the first. ADR-0023 promises views that provide "the
    // *other* arrangements", and the format has always allowed
    // `part-of: [concepts, consensus]` — but `.find()` here silently kept one and
    // discarded the rest, so a note could never appear in two groupings. The
    // model permitted it; the projection threw it away.
    const parents = [
      ...new Set(edges.filter((e) => e.from === n.id && e.kind === 'part-of').map((e) => e.to)),
    ];
    if (parents.length === 0) loose.push(n);
    else for (const p of parents) containers.set(p, [...(containers.get(p) ?? []), n]);
  }

  const lines = [HEADER('Index', 'The structure tree, projected from `part-of` edges.')];
  for (const container of [...containers.keys()].sort()) {
    lines.push(`## ${container}`, ``);
    for (const n of containers.get(container)!.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(bullet(n));
    }
    lines.push(``);
  }
  if (loose.length > 0) {
    lines.push(`## Unfiled`, ``);
    for (const n of loose.sort((a, b) => a.id.localeCompare(b.id))) lines.push(bullet(n));
    lines.push(``);
  }
  if (containers.size === 0 && loose.length === 0) lines.push(emptyNote('here yet'));

  return { path: '/index.md', content: lines.join('\n') };
}

/** Nodes something else supersedes — what grep cannot tell you is stale. */
export function generateSuperseded(nodes: Node[], edges: Edge[]): GeneratedFile {
  const superseded = new Map<string, string>();
  for (const e of edges) {
    if (e.kind === 'supersedes') superseded.set(e.to, e.from);
  }
  const lines = [
    HEADER(
      'Superseded',
      'Nodes something else replaced. Text search returns these with the same confidence as current ones; this is the difference.',
    ),
  ];
  const hits = nodes.filter((n) => superseded.has(n.id)).sort((a, b) => a.id.localeCompare(b.id));
  for (const n of hits) lines.push(`${bullet(n)} — superseded by \`${superseded.get(n.id)}\``);
  if (hits.length === 0) lines.push(emptyNote('is superseded'));
  return { path: `/${VIEWS_DIR}/superseded.md`, content: `${lines.join('\n')}\n` };
}

/** Most recently asserted first. Ties break by id so output is deterministic. */
export function generateRecent(nodes: Node[], limit = 50): GeneratedFile {
  const lines = [HEADER('Recent', 'Most recently asserted first.')];
  const sorted = [...nodes]
    .sort((a, b) =>
      a.stamp.at === b.stamp.at ? a.id.localeCompare(b.id) : b.stamp.at.localeCompare(a.stamp.at),
    )
    .slice(0, limit);
  for (const n of sorted) lines.push(`${bullet(n)} — ${n.stamp.at}`);
  if (sorted.length === 0) lines.push(emptyNote('captured yet'));
  return { path: `/${VIEWS_DIR}/recent.md`, content: `${lines.join('\n')}\n` };
}

/** Nodes with no edges in either direction — content nothing points at. */
export function generateOrphans(nodes: Node[], edges: Edge[]): GeneratedFile {
  const connected = new Set(edges.flatMap((e) => [e.from, e.to]));
  const lines = [
    HEADER(
      'Orphans',
      'Nodes with no relations in either direction — nothing points at them, and they point at nothing.',
    ),
  ];
  const hits = nodes.filter((n) => !connected.has(n.id)).sort((a, b) => a.id.localeCompare(b.id));
  for (const n of hits) lines.push(bullet(n));
  if (hits.length === 0) lines.push(emptyNote('is orphaned'));
  return { path: `/${VIEWS_DIR}/orphans.md`, content: `${lines.join('\n')}\n` };
}

/** Every derived file, for a given set of nodes and edges. */
export function generateAll(nodes: Node[], edges: Edge[], now: Instant): GeneratedFile[] {
  const live = nodes.filter((n) => !isExpired(n.stamp, now));
  return [
    generateIndex(live, edges),
    generateSuperseded(nodes, edges),
    generateRecent(nodes),
    generateOrphans(nodes, edges),
  ];
}
