/**
 * `doctor` — health, integrity, and the detective half of the guardrail story.
 *
 * **Read-only in Phase 9.** ADR-0028 makes not-rewriting-links engram's default
 * posture; `--fix` is its single exception and gets its own deliberate pass.
 *
 * §7 of the architecture is the reason this command matters: engram mediates only
 * two of the four write paths, because Obsidian and any agent with a shell write
 * files directly. A rule enforceable only at the write gate is therefore advisory.
 * Every closed relation was required in Phase 8 to carry a **detective form** —
 * this is where those get run.
 */

import { inspect, type Finding } from '../core/graph.js';
import type { Edge, Node } from '../core/model.js';
import { isDerived } from '../core/paths.js';
import type { Detector, FileStore } from '../core/ports.js';
import { getRelation, relationKinds } from '../core/relations.js';
import { walk, type WalkFinding } from './walk.js';
import { readNode } from '../format/registry.js';

export interface DoctorReport {
  /** Nothing here fails the command — ADR-0021 is explicit these are not errors. */
  warnings: string[];
  /** Only these make `doctor` exit non-zero. */
  failures: string[];
  /** The detective form of every registered relation, run and reported by name. */
  detectives: { relation: string; check: string; hits: string[] }[];
  counts: { nodes: number; edges: number };
}

const say = (f: Finding | WalkFinding): string => `[${f.code}] ${f.message}`;

export async function doctor(files: FileStore, detect: Detector): Promise<DoctorReport> {
  const warnings: string[] = [];
  const failures: string[] = [];

  const walked = await walk(files);
  for (const f of walked.findings) warnings.push(say(f));

  const nodes: Node[] = [];
  const edges: Edge[] = [];
  for (const path of walked.paths) {
    const raw = await files.read(path);
    if (raw === null) continue;
    const result = readNode(raw, path);
    nodes.push(result.node);
    edges.push(...result.edges);
    for (const w of result.warnings) warnings.push(`[read] ${path}: ${w}`);
  }

  for (const f of inspect(nodes, edges)) warnings.push(say(f));

  // A reserved path holding content no generator would write. The walker excludes
  // reserved paths from authored content, so without this check a hand-written
  // index.md would be invisible until reindex silently overwrote it.
  for (const path of await files.list()) {
    if (!isDerived(path)) continue;
    const raw = await files.read(path);
    if (raw !== null && raw.trim() !== '' && !raw.includes('GENERATED by engram reindex')) {
      warnings.push(
        `[derived-not-generated] ${path} is a derived path but was not written by engram. ` +
          `On conflict the rule is regenerate, never merge (ADR-0029) — run \`engram reindex\`.`,
      );
    }
  }

  // Detection over configuration (ADR-0025). Obsidian owns link rewriting; engram
  // only reports a mismatch (ADR-0028).
  if (await detect.has('obsidian')) {
    warnings.push(
      `[obsidian] Obsidian detected. Links must be set to absolute + markdown ` +
        `(Settings → Files & Links). Engram never rewrites link targets — Obsidian owns that (ADR-0028).`,
    );
  }

  const detectives = relationKinds().map((relation) => {
    const kind = getRelation(relation)!;
    const known = new Set(nodes.map((n) => n.id));
    const hits = edges
      .filter((e) => e.kind === relation && !known.has(e.to))
      .map((e) => `${e.from} --${relation}--> ${e.to} (target has no node)`);
    return { relation, check: kind.detective, hits };
  });

  return { warnings, failures, detectives, counts: { nodes: nodes.length, edges: edges.length } };
}

/** Format a report for a terminal. Exit code is `failures.length === 0 ? 0 : 1`. */
export function formatReport(r: DoctorReport): string {
  const lines = [`engram doctor`, ``, `nodes: ${r.counts.nodes}   edges: ${r.counts.edges}`, ``];

  if (r.failures.length > 0) {
    lines.push(`FAILURES (${r.failures.length})`, ...r.failures.map((f) => `  ✖ ${f}`), ``);
  }
  if (r.warnings.length > 0) {
    lines.push(
      `warnings (${r.warnings.length}) — none of these are errors`,
      ...r.warnings.map((w) => `  • ${w}`),
      ``,
    );
  }

  lines.push(`detective checks (${r.detectives.length} registered relations)`);
  for (const d of r.detectives) {
    lines.push(`  ${d.relation}: ${d.check}`);
    for (const h of d.hits) lines.push(`    • ${h}`);
    if (d.hits.length === 0) lines.push(`    clean`);
  }

  if (r.failures.length === 0 && r.warnings.length === 0) lines.push(``, `no problems found`);
  return `${lines.join('\n')}\n`;
}
